language: node_js
jobs:
  include:
    - node_js: "stable"
      name: "Test-Environments"
      sudo: required
      dist: trusty
      addons:
        # firefox: latest
        chrome: stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      script: "npm run test:ci:env"
    - node_js: "stable"
      script: "npm run test:ci"
    - node_js: "10"
      script: "npm run test:ci"
